### ISSUE TITLE
MP Config Converters Interface

### ISSUE THREAD

**Issue by radcortez** [smallrye/smallrye-converters#1]
Right now, since the code was ported from SmallRye Config, it also brought the MP Config API and the dependency of the Converter interface.

Most likely, we want to drop that dependency and add our own Converter interface. We can then add a new module to bridge between the new interface and the one in MP Config.

What do you think @dmlloyd ?

**Comment by dmlloyd** [comment]
I agree.

**Comment by radcortez** [comment]
Cool, I'll work on that!
